name: blott
description: "Blott is news app that provides you with the latest news from all
  over the world"

# The following line prevents the package from being accidentally published to pub.dev.
publish_to: 'none'

# The following defines the version and build number for your application.
version: 1.0.0+1

# The following line ensures that the package versions are locked to the versions
environment:
  sdk: '>=3.4.4 <4.0.0'

# Add dependencies here
dependencies:
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  device_preview: ^1.2.0
  dio: ^5.7.0
  dio_http_cache_fix: ^0.5.1
  dio_smart_retry: ^6.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.4.1
  flutter_svg: ^2.0.10+1
  flutter_vibrate: ^1.3.0
  flutternativedata: ^1.0.2
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  get_it: ^8.0.0
  google_fonts: ^6.2.1
  hive_flutter: ^1.1.0
  injectable: ^2.4.4
  internet_connection_checker: ^1.0.0+1
  json_annotation: ^4.9.0
  logger: ^2.4.0
  page_transition: ^2.1.0
  pretty_dio_logger: ^1.4.0
  rename: ^3.0.2
  retrofit: ^4.4.1
  rxdart: ^0.28.0
  shimmer: ^3.0.0
  toastification: ^2.3.0
  uuid: ^4.5.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.7.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  hive_generator: ^2.0.1
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  retrofit_generator: ^9.1.2

dependency_overrides:
  get_it: ^7.7.0
  meta: ^1.14.0

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - .env

flutter_native_splash:
  android: true
  ios: true
  color: "#000000"
  image: assets/images/app_icon.png
  android_12:
    image: assets/images/app_icon.png
